-- SQL for creating the user_quiz_attempts table

CREATE TABLE public.user_quiz_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    quiz_id INTEGER NOT NULL, -- Corresponds to Quiz.id from local data
    course_id INTEGER NOT NULL, -- Corresponds to Quiz.courseId from local data
    score INTEGER NOT NULL,
    total_possible INTEGER NOT NULL,
    answers JSONB NOT NULL, -- Stores the QuizAttempt['answers'] array
    attempt_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Constraints
    CONSTRAINT score_non_negative CHECK (score >= 0),
    CONSTRAINT total_possible_positive CHECK (total_possible > 0)
);

-- Optional: Add comments
COMMENT ON TABLE public.user_quiz_attempts IS 'Stores user attempts for quizzes.';
COMMENT ON COLUMN public.user_quiz_attempts.quiz_id IS 'Identifier for the quiz taken (from local quizData.ts).';
COMMENT ON COLUMN public.user_quiz_attempts.course_id IS 'Identifier for the course associated with the quiz.';
COMMENT ON COLUMN public.user_quiz_attempts.answers IS 'JSON array of user answers, structure: [{ questionId: number, userAnswer: string | string[], isCorrect: boolean }].';

-- Function to update updated_at timestamp (if not already existing from other tables)
-- CREATE OR REPLACE FUNCTION public.trigger_set_timestamp()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   NEW.updated_at = NOW();
--   RETURN NEW;
-- END;
-- $$ LANGUAGE plpgsql;

-- Trigger to update updated_at on row update
CREATE TRIGGER set_user_quiz_attempts_updated_at
BEFORE UPDATE ON public.user_quiz_attempts
FOR EACH ROW
EXECUTE FUNCTION public.trigger_set_timestamp(); -- Assuming trigger_set_timestamp function exists

-- RLS Policies Recommendations (similar to user_purchases)
-- ALTER TABLE public.user_quiz_attempts ENABLE ROW LEVEL SECURITY;

-- Allow users to view their own attempts
-- CREATE POLICY "Allow users to view their own quiz attempts"
-- ON public.user_quiz_attempts
-- FOR SELECT
-- USING (auth.uid() = user_id);

-- Allow users to insert their own attempts
-- CREATE POLICY "Allow users to insert their own quiz attempts"
-- ON public.user_quiz_attempts
-- FOR INSERT
-- WITH CHECK (auth.uid() = user_id);

-- Disallow direct updates/deletes by users (usually handled by application logic if needed)
-- CREATE POLICY "Disallow direct update of quiz attempts by users"
-- ON public.user_quiz_attempts
-- FOR UPDATE
-- USING (false);

-- CREATE POLICY "Disallow direct delete of quiz attempts by users"
-- ON public.user_quiz_attempts
-- FOR DELETE
-- USING (false);

SELECT 'User quiz attempts table schema created successfully in user_quiz_attempts_schema.sql';
