-- SQL for creating the user_purchases table

CREATE TABLE public.user_purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    item_id TEXT NOT NULL, -- Stores course_id or plan_identifier
    item_type TEXT NOT NULL CHECK (item_type IN ('course', 'subscription_plan')),
    purchase_date TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    price_paid NUMERIC(10, 2) NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    purchase_status TEXT NOT NULL DEFAULT 'completed' CHECK (purchase_status IN ('completed', 'pending', 'failed', 'refunded')),
    payment_gateway_transaction_id TEXT,
    subscription_start_date TIMESTAMPTZ,
    subscription_end_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,

    -- Constraints
    CONSTRAINT price_paid_non_negative CHECK (price_paid >= 0),
    CONSTRAINT subscription_dates_valid CHECK (subscription_start_date IS NULL OR subscription_end_date IS NULL OR subscription_start_date <= subscription_end_date)
);

-- Optional: Add a comment to the table or columns
COMMENT ON TABLE public.user_purchases IS 'Stores records of user purchases for courses and subscription plans.';
COMMENT ON COLUMN public.user_purchases.item_id IS 'Identifier for the purchased item, e.g., course_id or subscription plan code.';
COMMENT ON COLUMN public.user_purchases.item_type IS 'Type of item purchased: ''course'' or ''subscription_plan''.';
COMMENT ON COLUMN public.user_purchases.purchase_status IS 'Status of the purchase transaction.';
COMMENT ON COLUMN public.user_purchases.subscription_start_date IS 'Start date for a subscription, if applicable.';
COMMENT ON COLUMN public.user_purchases.subscription_end_date IS 'End date for a subscription, if applicable.';


-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.trigger_set_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger to update updated_at on row update
CREATE TRIGGER set_user_purchases_updated_at
BEFORE UPDATE ON public.user_purchases
FOR EACH ROW
EXECUTE FUNCTION public.trigger_set_timestamp();

-- Recommendations for Row Level Security (RLS)
-- These should be run after the table is created.

-- 1. Enable RLS on the table
-- ALTER TABLE public.user_purchases ENABLE ROW LEVEL SECURITY;

-- 2. Create a policy for users to view their own purchases
-- CREATE POLICY "Allow users to view their own purchases"
-- ON public.user_purchases
-- FOR SELECT
-- USING (auth.uid() = user_id);

-- 3. Create a policy for allowing service roles or admins to access all data (if needed)
-- CREATE POLICY "Allow admin full access"
-- ON public.user_purchases
-- FOR ALL
-- USING (true) -- Or a more specific check like checking a custom claim for admin role
-- WITH CHECK (true);

-- Note: For INSERT, UPDATE, DELETE policies, you'd typically want more restrictive rules.
-- For example, users should probably not be able to update their own purchase records directly after creation,
-- or insert them without going through a payment process. These operations are often handled by backend functions
-- running with elevated privileges (`service_role` key) or specific triggers/functions.

-- Example: Policy to prevent users from updating/deleting their purchases directly
-- CREATE POLICY "Disallow direct update or delete by users"
-- ON public.user_purchases
-- FOR UPDATE
-- USING (false);

-- CREATE POLICY "Disallow direct delete by users"
-- ON public.user_purchases
-- FOR DELETE
-- USING (false);

-- Inserts should ideally be handled by a secure backend function or a trigger initiated by a payment confirmation.
-- If direct inserts were allowed (not recommended for purchases):
-- CREATE POLICY "Allow users to insert their own purchases"
-- ON public.user_purchases
-- FOR INSERT
-- WITH CHECK (auth.uid() = user_id);

-- Consider unique constraints if necessary, e.g., a user can only have one active subscription of a certain type.
-- This might be better handled at the application logic level or with a more complex partial unique index.
-- Example: User can only have one 'active' subscription for a specific item_id of type 'subscription_plan'
-- CREATE UNIQUE INDEX unique_active_subscription_per_user
-- ON public.user_purchases (user_id, item_id, item_type)
-- WHERE (item_type = 'subscription_plan' AND purchase_status = 'completed' AND (subscription_end_date IS NULL OR subscription_end_date >= NOW()));
-- The above unique index is an example and might need adjustment based on how "active" is defined.
-- For instance, if `purchase_status` can also be 'active' instead of just 'completed' for subscriptions.
-- It's often simpler to manage this in application logic when a new subscription is created.

SELECT 'User purchases table schema created successfully in user_purchases_schema.sql';
